# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

#pool:
#  vmImage: ubuntu-latest

jobs:
- deployment: Run_E2E_Tests
  pool:
    vmImage: ubuntu-20.04
  container: mcr.microsoft.com/playwright:v1.29.2-focal
  environment: testing
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - task: Bash@3
          displayName: 'Run Playwright tests'
          env:
            CI: true
          inputs:
            workingDirectory: 'tests'
            targetType: 'inline'
            failOnStderr: true
            script: |
              npm ci
              env
              npx playwright test --reporter=junit
        - task: PublishTestResults@2
          displayName: 'Publish test results'
          inputs:
            searchFolder: 'TestResults'
            testResultsFormat: 'JUnit'
#            testResultsFiles: 'e2e-junit-results.xml' 
            testResultsFiles: '**/*-results.xml' 
            mergeTestResults: true
            failTaskOnFailedTests: true
            testRunTitle: 'End-To-End Tests'
          condition: succeededOrFailed()
